server:
  port: 8090

spring:
  application:
    name: lab
  datasource:
    username: root
    password: Ab123654
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.27.118:3306/lab

